title: LY
author: @Jenuaz
email: lysiak.yevhenii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is LY blog page. Purpose of this blog is self-development and SMART management.
  Also I hope this page will help others in their aims.
# social links
twitter_username: YevheniiLysiak # DO NOT include the @ character, or else the build will fail!
github_username:  Jenuaz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
